### PR TITLE
[Improvement] Fixed code quality issues 

### PR DESCRIPTION
**Pull request by withshubh**
##### Description
Hi :wave: 
I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/kubeaudit/issues/?category=recommended).

### Summay of changes

- Remove unnecessary comparison with bool
- Combine multiple `append`s into a single call
- Fix check for empty string
- Add .deepsource.toml config

##### Type of change

- [x] Bug fix :bug:

##### Checklist:
- [x] I have signed the appropriate [Contributor License Agreement](https://cla.shopify.com/)

### CODE REVIEW

**Comment by withshubh** [comment]
I've signed the CLA!

**Comment by genevieveluyt** [comment]
Hey @withshubh ,

Thanks for your contribution! I'm not sure what's up with the CLA bot. I think it may be confused because DeepSource Bot is listed as a contributor. Would you be willing to open a new PR and make the changes manually, such that you are the only contributor?

**Comment by withshubh** [comment]
@genevieveluyt fixed it :sparkles:

**Review by genevieveluyt — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
