### PR TITLE
Kubeaudit Package

### LINKED ISSUE #239: Kubeaudit Package
##### ISSUE TYPE
 - [ ] Bug Report
 - [x] Feature Idea

# FEATURE IDEA

- [x] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:** 
Make kubeaudit importable as a package rather than only a CLI.

<sup><small>1</small></sup> <sub>This is the quickest way to get a new feature! We reserve the right to close feature requests, even ones we like, if the proposer does not intend to contribute to the feature and it doesn't fit in our current roadmap.</sub>

### PR DESCRIPTION
**Pull request by genevieveluyt**
Makes it so you can use kubeaudit as a package and as a CLI!

Closes #239 and probably also #235, #233, #242, #269, and #270

This PR will be an accumulation of multiple PRs making up the work of converting kubeaudit into a package. It is meant to track completed and pending work.

- [x] Base PR (all shared logic) #234 
- [x] Open separate PRs for each auditor and merge them into this one
    - [x] AppArmor #234 
    - [x] Automount Service Account Token #244
    - [x] Capabilities #255
    - [x] Host Namespaces #245
    - [x] Image #246
    - [x] Limits #247 
    - [x] Docker Socket Mounted #248
    - [x] Default Deny Network Policies #249
    - [x] RunAsNonRoot #250
    - [x] AllowPrivilegeEscalation #251
    - [x] Privileged #252
    - [x] ReadOnlyRootFilesystem #253
    - [x] Seccomp #254
- [x] Add all the auditors to `auditors/all/all.go` and uncomment the autofix tests #256 
- [x] Add the CLI code #258 
- [x] Add demo code #259 
- [x] Update the readme #261 
- [x] Test #274

### CODE REVIEW

**Comment by genevieveluyt** [comment]
Hey @mike-stewart, are you still interested in beta-testing the new version of kubeaudit? 🙂

**Comment by mike-stewart** [comment]
@genevieveluyt Happy to give it a run on some of our stacks. Should I build from source or is a package available?

**Comment by genevieveluyt** [comment]
@mike-stewart that would be awesome! Could you try building from source on the `release` branch? Instructions for that can be found in the [README on the branch](https://github.com/Shopify/kubeaudit/tree/release#installation). There are some minor changes between this version of kubeaudit and the old one, namely the configuration file format if you used that previously, which can be found in that README as well. And if you have any feedback to improve the README I'd love to hear that as well 🙂

**Comment by genevieveluyt** [comment]
@mike-stewart Hmm it seems to work for me. Could you tell me exactly what steps you followed and what version of golang you're using?

This is what I did:
1. `git checkout release`
1. `make`
1. Copy https://github.com/coreos/kube-prometheus/blob/b6ad6644d5ceef9a854d78d1f1e284a68dbb4d94/manifests/setup/prometheus-operator-0alertmanagerCustomResourceDefinition.yaml into `manifest.yaml`
1. `./kubeaudit all -f manifest.yaml`

Using `go version go1.13 darwin/amd64`

I got no output which is expected because it's a custom resource and we have no way of knowing what security controls exist for custom resources, so we can't really audit them.

I will add this into the README as well, but the currently supported resources are:
- Cronjob
- DaemonSet
- Deployment
- PodTemplate
- ReplicationController
- StatefulSet
- Pod
- Namespace

**Pull request merged**
