### PR TITLE
README: Updates link to config/caps

### PR DESCRIPTION
**Pull request by schnatterer**
##### Description

Fixes link behind "config/caps" in the README.md

### CODE REVIEW

**Comment by schnatterer** [comment]
Neither https://github.com/Shopify/kubeaudit#contribute nor https://github.com/Shopify/kubeaudit/blob/master/CODE_OF_CONDUCT.md giving me any hints about the CLA.
And it's only just a link I fixed. Maybe that's a bit too much of a fuss.

**Comment by catherinejones** [comment]
Hi @schnatterer! I'm sorry for missing this, the CLA form is here: https://cla.shopify.com/! Let me know if you have any questions, I'm sorry this was so difficult to find (it took me a minute too!)

**Comment by schnatterer** [comment]
@catherinejones Thanks, signed! How to rerun the check?

**Comment by genevieveluyt** [comment]
Hey @schnatterer, thanks for your contribution! You can re-run the check by commenting
```
I've signed the CLA!
```

**Comment by genevieveluyt** [comment]
I've signed the CLA!

**Pull request merged**
