### PR TITLE
Add auth support for azure, exec, oidc, openstack

### LINKED ISSUE #314: OIDC authentication does not work in recent versions
##### ISSUE TYPE
 - [X] Bug Report
 - [ ] Feature Idea

# BUG REPORT

##### SUMMARY
OIDC authentication does not work on version 0.9.0 and up, apparently because the OIDC auth provider is either not present or not detected correctly.

##### ENVIRONMENT
* Kubeaudit version: 0.11.5 / 0.11.0 / 0.9.0 (0.8.0 not impacted)
* Kubeaudit install method: Binary

##### STEPS TO REPRODUCE

- Create a kubeconfig file with oidc authentication
- Run kubectl to make sure config / authentication works
- Run kubeaudit in local mode, e.g. `./kubeaudit all`

##### EXPECTED RESULTS

Audit results

##### ACTUAL RESULTS

- v0.8.0: audit results
- v0.9.0/0.11.0/0.11.5: error message: `level=fatal msg="Error auditing cluster in local mode" error="no Auth Provider found for name \"oidc\"`

### PR DESCRIPTION
**Pull request by genevieveluyt**
##### Description

Fixes #314

##### Type of change

- [x] Bug fix :bug:
- [ ] New feature :sparkles:
- [ ] This change requires a documentation update :book:
- [ ] Breaking changes :warning:

##### Checklist:

- [ ] I have :tophat: my changes (A 🎩 specifically includes pulling down changes, setting them up, and manually testing the changed features and potential side effects to make sure nothing is broken)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The test coverage did not decrease
- [ ] I have signed the appropriate [Contributor License Agreement](https://cla.shopify.com/)

### CODE REVIEW

**Comment by genevieveluyt** [comment]
Hi @clavoillotte, I've made a [prelease](https://github.com/Shopify/kubeaudit/releases/tag/v0.11.7-alpha) with the changes in this PR. Would you mind trying it out and seeing if OIDC auth works for you now?

**Review by cjones-shopify — APPROVED** [review]
:shipit:!

**Comment by clavoillotte** [comment]
> Hi @clavoillotte, I've made a [prelease](https://github.com/Shopify/kubeaudit/releases/tag/v0.11.7-alpha) with the changes in this PR. Would you mind trying it out and seeing if OIDC auth works for you now?

Sorry I missed your message. I don't have access to the environment I encountered #314 on anymore, but I'll give it a try next time I get access to one with OIDC authentication and report here.
Many thanks for the fix!

**Comment by genevieveluyt** [comment]
No problem, if you have a chance to try it out in the future and it doesn't work feel free to open a new issue. Cheers!

**Comment by clavoillotte** [comment]
A teammate was able to test the latest release (0.12.0) on an environment with OIDC authentication, and it worked perfectly. Thanks again!

**Comment by genevieveluyt** [comment]
Awesome, thanks for the update!

**Pull request merged**
