### PR TITLE
Fix deadlink in seccomp auditor docs

### PR DESCRIPTION
**Pull request by bvwells**
##### Description

Replace dead link to gardener.cloud seccomp tutorial with official kubernetes seccomp tutorial.

##### Type of change

- [x] Bug fix :bug:
- [ ] New feature :sparkles:
- [ ] This change requires a documentation update :book:
- [ ] Breaking changes :warning:

### CODE REVIEW

**Review by genevieveluyt — APPROVED** [review]
Thanks!

**Comment by bvwells** [comment]
@genevieveluyt was just about to message you! You're quick! :-)

**Comment by genevieveluyt** [comment]
Looks like the CLA check passed at least 🎉

**Comment by bvwells** [comment]
Thanks @genevieveluyt for all your help with this!

**Comment by genevieveluyt** [comment]
You're welcome! Thanks for the contribution!

**Pull request merged**
