### PR TITLE
Fixes #41: Update all dependencies to the current master

### LINKED ISSUE #41: Update all dependencies
Kubeaudit currently has a couple of older dependencies. Would be great to make Kubeaudit run on the never versions of all the dependencies.

### PR DESCRIPTION
**Pull request by jinankjain**
Update all dependencies to current master

### CODE REVIEW

**Comment by csgregorian** [comment]
Does this make it go gettable by fixing the kubernetes version we pull?

**Comment by jinankjain** [comment]
How does it depend on `kubernetes`  version because `kubernetes` is not a dependency?

**Comment by csgregorian** [comment]
The `k8s` go package versions, rather

**Comment by jinankjain** [comment]
I think it should work assuming that I did not break anything in CI :crossed_fingers:

**Pull request merged**
