### PR TITLE
[WIP] No dev but manul

### PR DESCRIPTION
**Pull request by klautcomputing**
Currently the project still relies on `dev` which it shouldn't. Also, the project is not `go get`-able at the moment which it arguably should be.

The current state builds but for some reason travis doesn't like it, yet(?). I am gonna figure stuff out.

### CODE REVIEW

**Comment by klautcomputing** [comment]
Figured stuff out :)

**Comment by klautcomputing** [comment]
Open todos:
- [ ] see whether it `go get`(s)
- [ ] delete the dev.yml file
- [ ] update the make file
- [ ] make sure everything works again

**Comment by jinankjain** [comment]
Adding submodules is tricky as they are hard to manage. Git submodules needs a lot a maintenance as whenever anyone updates those submodules `original master` also needs to be bumped.

Travis can support glide but you need to add glide in the travis build dependency.

**Comment by klautcomputing** [comment]
I don't agree with your judgement on them being hard to manage, you can easily do that with https://github.com/kovetskiy/manul

**Comment by klautcomputing** [comment]
closing since we merged #39

**Pull request closed without merging**
